fos_elastica:
    clients:
        default: { host: 'localhost', port: '9209' }
#    indexes:
#        book:
#            properties:
#                name: ~
#            persistence:
#                driver: orm
#                model: App\Entity\Company
#                provider: ~
#                finder: ~
#                repository: App\Repository\BookRepository
