vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: '%path_products_images%'
            upload_destination: '%kernel.project_dir%/public%path_products_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false # obliger de ne pas supprimer les fichier update
            delete_on_remove: false
